# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "srv-dns" do |dns|
    dns.vm.hostname = "srv-dns"
    dns.vm.network "private_network", ip: "192.168.56.10"

    dns.vm.provider "virtualbox" do |vb|
      vb.name = "MGGT1103-DNS-Server"
      vb.memory = "768"
      vb.cpus = 1
      vb.gui = false
    end

    dns.vm.provision "shell", path: "scripts/provision-dns.sh"
  end

  config.vm.define "srv-web" do |web|
    web.vm.hostname = "srv-web"
    web.vm.network "private_network", ip: "192.168.56.20"

    web.vm.provider "virtualbox" do |vb|
      vb.name = "MGGT1103-Web-Server"
      vb.memory = "768"
      vb.cpus = 1
      vb.gui = false
    end

    web.vm.provision "shell", path: "scripts/provision-web.sh"
  end

  config.vm.define "client-test" do |client|
    client.vm.hostname = "client-test"
    client.vm.network "private_network", ip: "192.168.56.30"

    client.vm.provider "virtualbox" do |vb|
      vb.name = "MGGT1103-Client-Test"
      vb.memory = "512"
      vb.cpus = 1
      vb.gui = false
    end

    client.vm.provision "shell", path: "scripts/provision-client.sh"
  end
end
